<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CashFlowCraft</title>
    <link rel="stylesheet" href="styles.css"> <!-- Verlinke deine CSS-Datei hier -->
    <script src="scripts.js"></script> <!-- Verlinke deine JavaScript-Datei hier -->
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
</head>
<body>
    <header>
        <h1>CashFlowCraft</h1>
        
    </header>
    <nav style="height: max-content 2px;">
        <div class="welcome-grid">
            <h2>Wilkommen x</h2>
        </div>
    </nav>
    <main>
        <div class="content-grid2">
            <table style="margin: auto;">
                <caption>Kostenaufstellung</caption>
                <tr>
                <th>Wie viel</th>
                <th>Wieso</th>
                <th>Wann</th>
                </tr>
                <tr>
                <th>Miete</th>
                <td>1.000,-</td>
                <td>1.000,-</td>
                </tr>
                <tr>
                <th>Nahrung</th>
                <td>1.000,-</td>
                <td>1.000,-</td>
                </tr>
                <tr>
                <th>Freizeit</th>
                <td>1.000,-</td>
                <td>1.000,-</td>
                </tr>
            </table>
        </div>
            <div class="button-container">
                <button onclick="Logout()">Abmeldung</button><br>
            </div>

    </main>
    <footer>
        <p>Impressum</p>
        <p1>Kontakt: <a href="mailto:hege@example.com">cashflowcraft@example.com</a></p1>
    </footer>

</body>
</html>
